name: Update Docker and Deploy (Production)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-docker:
    uses: RDGAapp/database/.github/workflows/build_push.yml@main
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DATABASE: ${{ secrets.DATABASE }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
